baseURL = "https://junpoyu.github.io"
theme = "FixIt"
title = "Junpo Yu's Blog"
languageCode = "zh-CN"

# 默认语言
defaultContentLanguage = "zh-CN"
ignoreLogs = ['warning-goldmark-raw-html']
# 是否使用 robots.txt
enableRobotsTXT = true
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true

# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# 分页配置
[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

# 语言设置
[languages]
  [languages.zh-CN]
    weight = 1
    # 网站语言, 仅在这里 CN 大写
    languageCode = "zh-CN"
    # 语言名称
    languageName = "简体中文"
    # 是否包括中日韩文字
    hasCJKLanguage = true
    # 网站标题
    title = "Junpo Yu's Blog"
    # 版权描述，仅仅用于 SEO
    copyright = ""

    contentDir = "content/posts"
    disablePathToLower = true
    
    # 菜单配置
    [languages.zh-CN.menu]
      [[languages.zh-CN.menu.main]]
        weight = 1
        identifier = "tech"
        pre = ""
        post = ""
        name = "技术性文章"
        url = "/posts/tech/"
        title = ""
      [[languages.zh-CN.menu.main]]
        weight = 2
        identifier = "builds"
        pre = ""
        post = ""
        name = "构建"
        url = "/posts/builds/"
        title = ""
      [[languages.zh-CN.menu.main]]
        weight = 3
        identifier = "knowledge"
        pre = ""
        post = ""
        name = "理论知识"
        url = "/posts/knowledge/"
        title = ""
      [[languages.zh-CN.menu.main]]
        weight = 4
        identifier = "research"
        pre = ""
        post = ""
        name = "科研相关"
        url = "/posts/research/"
        title = ""
      [[languages.zh-CN.menu.main]]
        weight = 5
        identifier = "life"
        pre = ""
        post = ""
        name = "生活"
        url = "/posts/life/"
        title = ""
      [[languages.zh-CN.menu.main]]
        weight = 6
        identifier = "index"
        pre = ""
        post = ""
        name = "索引"
        url = ""
        title = ""
      [[languages.zh-CN.menu.main]]
        parent = "index"
        weight = 7
        identifier = "archives"
        pre = ""
        post = ""
        name = "归档"
        url = "/archives/"
        title = ""
      [[languages.zh-CN.menu.main]]
        parent = "index"
        weight = 8
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
      [[languages.zh-CN.menu.main]]
        parent = "index"
        weight = 9
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
      [[languages.zh-CN.menu.main]]
        parent = "index"
        weight = 10
        identifier = "collections"
        pre = ""
        post = ""
        name = "合集"
        url = "/collections/"
        title = ""
    
    # 中文参数
    [languages.zh-CN.params]
      # 网站描述
      description = "你所经历的每一个日常，也许正是连续不断的奇迹"
      # 作者配置
      [languages.zh-CN.params.author]
        name = "Junpo Yu"
        email = "junpo_yu@163.com"
        link = "https://junpoyu.github.io/"
        avatar = "/rubysiu.jpg"
      
      # 页面头部导航栏标题配置
      [languages.zh-CN.params.header.title]
        # 标题名称
        name = "Junpo Yu's Blog"
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = ""
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
      
      # 主页配置
      [languages.zh-CN.params.home.profile]
        # 主页显示的网站标题
        title = "Junpo Yu's Blog"
        # 主页显示的网站副标题
        subtitle = "你所经历的每一个日常，也许正是连续不断的奇迹"
      
      # Cookie 许可配置
      [languages.zh-CN.params.cookieconsent.content]
        message = "此网站使用 Cookie 来改善您的浏览体验。"
        dismiss = "同意"
        link = "了解更多"


  [languages.en]
    weight = 2
    # 网站语言
    languageCode = "en"
    # 语言名称
    languageName = "English"
    # 网站标题
    title = "Junpo Yu's Blog"
    # 版权描述，仅仅用于 SEO
    copyright = ""
    
    # 菜单配置
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "tech"
        pre = ""
        post = ""
        name = "Tech Articles"
        url = "/posts/tech/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "builds"
        pre = ""
        post = ""
        name = "Builds"
        url = "/posts/builds/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "knowledge"
        pre = ""
        post = ""
        name = "Knowledge"
        url = "/posts/knowledge/"
        title = ""
      [[languages.en.menu.main]]
        weight = 4
        identifier = "research"
        pre = ""
        post = ""
        name = "Research"
        url = "/posts/research/"
        title = ""
      [[languages.en.menu.main]]
        weight = 5
        identifier = "life"
        pre = ""
        post = ""
        name = "Life"
        url = "/posts/life/"
        title = ""
      [[languages.en.menu.main]]
        weight = 6
        identifier = "index"
        pre = ""
        post = ""
        name = "Index"
        url = ""
        title = ""
      [[languages.en.menu.main]]
        parent = "index"
        weight = 7
        identifier = "archives"
        pre = ""
        post = ""
        name = "Archives"
        url = "/archives/"
        title = ""
      [[languages.en.menu.main]]
        parent = "index"
        weight = 8
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
      [[languages.en.menu.main]]
        parent = "index"
        weight = 9
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
      [[languages.en.menu.main]]
        parent = "index"
        weight = 10
        identifier = "collections"
        pre = ""
        post = ""
        name = "Collections"
        url = "/collections/"
        title = ""
    
    # 英文参数
    [languages.en.params]
      # 网站描述
      description = "Every ordinary day you experience may be a continuous miracle"
      # 作者配置
      [languages.en.params.author]
        name = "Junpo Yu"
        email = "junpo_yu@163.com"
        link = "https://junpoyu.github.io/"
        avatar = "/rubysiu.jpg"
      
      # 页面头部导航栏标题配置
      [languages.en.params.header.title]
        # 标题名称
        name = "Junpo Yu's Blog"
        # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
        pre = ""
        # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
        post = ""
      
      # 主页配置
      [languages.en.params.home.profile]
        # 主页显示的网站标题
        title = "Junpo Yu's Blog"
        # 主页显示的网站副标题
        subtitle = "Every ordinary day you experience may be a continuous miracle"
      
      # Cookie 许可配置
      [languages.en.params.cookieconsent.content]
        message = "This website uses Cookies to improve your experience."
        dismiss = "Accept"
        link = "Learn more"

[params]
  # 网站默认主题样式 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  #  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  #  日期格式
  dateFormat = "2006-01-02"
  # 网站标题, 用于 Open Graph 和 Twitter Cards
  title = "Junpo Yu's Blog"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/logo.png"]

  # 页面头部导航栏配置
  [params.header]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode = "auto"
    #  页面头部导航栏标题配置
    [params.header.title]
      # LOGO 的 URL
      logo = "/rubysiu.jpg"
      #  是否为标题显示打字机动画
      typeit = false

  # 页面底部信息配置
  [params.footer]
    enable = true
    copyright = true
    author = true
    since = "2024"
    gov = ""
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    [params.footer.powered]
      enable = true
      hugoLogo = true
      themeLogo = true
    [params.footer.siteTime]
      enable = true
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "2024-09-12T00:00:00+08:00"
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0

  #  Section (所有文章) 页面配置
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    [params.section.feed]
      limit = -1
      fullText = false

  #  List (目录或标签) 页面配置
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    [params.list.feed]
      limit = -1
      fullText = false

  [params.tagcloud]
    enable = true
    min = 14
    max = 32
    peakCount = 10
    orderby = "count"

  [params.backToTop]
    enable = true
    scrollpercent = true
  #  应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "Junpo Yu's Blog"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"

  #  搜索配置
  [params.search]
    enable = true
    type = "fuse"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false

  # 主页配置
  [params.home]
    #  RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "/rubysiu.jpg"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
      #  免责声明 (支持 HTML 格式)
      disclaimer = ""
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      #  被 params.page 中的 hiddenFromHomePage 替代
      # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

  # 作者的社交信息设置
  [params.social]
    GitHub = "JunpoYu"
    Email = "junpo_yu@163.com"
    RSS = true # 

  #  文章页面全局配置
  [params.page]
    #  是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    #  是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    #  是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    #  是否使用 ruby 扩展语法
    ruby = true
    #  是否使用 fraction 扩展语法
    fraction = true
    #  是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    #  是否在 RSS 中显示全文内容
    rssFullText = false
    #  目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      #  是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
    #  代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 50
    #  KaTeX 数学公式
    [params.page.math]
      enable = true
      type = "mathjax"
      # MathJax server-side rendering (https://www.mathjax.org)
      # MathJax config: https://docs.mathjax.org/en/latest/options/index.html
      [params.page.math.mathjax]
        cdn = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
        [params.page.math.mathjax.packages]
          # '[+]' = ['configmacros']
        # custom macros map
        # syntax: <macro> = <definition>
        [params.page.math.mathjax.macros]
          # "bold" = ["{\\bf #1}", 1]   # usage: $\bold{math}$
        [params.page.math.mathjax.loader]
          load = ['ui/safe']
          [params.page.math.mathjax.loader.paths]
            # custom = "https://cdn.jsdelivr.net/gh/sonoisa/XyJax-v3@3.0.1/build/"
          # more loader config e.g source, dependencies, provides etc.
        [params.page.math.mathjax.options]
          enableMenu = true
          # more options e.g. skipHtmlTags, ignoreHtmlClass etc.
    [params.page.mapbox]
      # Mapbox GL JS 的 access token
      accessToken = ""
      # 浅色主题的地图样式
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      # 深色主题的地图样式
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      # 是否添加 NavigationControl
      navigation = true
      # 是否添加 GeolocateControl
      geolocate = true
      # 是否添加 ScaleControl
      scale = true
      # 是否添加 FullscreenControl
      fullscreen = true
    #  文章页面的分享信息设置
    [params.page.share]
      enable = true
      X = true # 
      Twitter = false # 
      Threads = true # 
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = true
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Diaspora = true # 
      Mix = false
      Telegram = true # 
    #  评论系统设置
    [params.page.comment]
      enable = false
      # Disqus 评论系统设置
      [params.page.comment.disqus]
        # 
        enable = false
        # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
        shortname = ""
      # Gitalk 评论系统设置
      [params.page.comment.gitalk]
        # 
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      # Valine 评论系统设置
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        # 为空时自动适配当前主题 i18n 配置
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        #  emoji 数据文件名称, 默认是 "google.yml"
        # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
        # 位于 "themes/LoveIt/assets/lib/valine/emoji/" 目录
        # 可以在你的项目下相同路径存放你自己的数据文件:
        # "assets/lib/valine/emoji/"
        emoji = ""
      # Facebook 评论系统设置
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        # 为空时自动适配当前主题 i18n 配置
        languageCode = "zh_CN"
      #  Telegram Comments 评论系统设置
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      #  Commento 评论系统设置
      [params.page.comment.commento]
        enable = false
      #  utterances 评论系统设置
      [params.page.comment.utterances]
        enable = false
        # owner/repo
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      # giscus comment 评论系统设置 (https://giscus.app/zh-CN)
      [params.page.comment.giscus]
        # 你可以参考官方文档来使用下列配置
        enable = false
        repo = ""
        repoId = ""
        category = "Announcements"
        categoryId = ""
        # 为空时自动适配当前主题 i18n 配置
        lang = ""
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false
        lightTheme = "light"
        darkTheme = "dark"
    #  第三方库配置
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # 位于 "assets/"
        # 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # 位于 "assets/"
        # 或者
        # someJavascript = "https://cdn.example.com/some.js"
    #  页面 SEO 配置
    [params.page.seo]
      # 图片 URL
      images = []
      # 出版者信息
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  #  TypeIt 配置
  [params.typeit]
    # 每一步的打字速度 (单位是毫秒)
    speed = 100
    # 光标的闪烁速度 (单位是毫秒)
    cursorSpeed = 1000
    # 光标的字符 (支持 HTML 格式)
    cursorChar = "|"
    # 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
    duration = -1

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  #  网站 SEO 配置
  [params.seo]
    # 图片 URL
    image = ""
    # 缩略图 URL
    thumbnailUrl = ""

  #  网站分析配置
  [params.analytics]
    # 
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-LNVWEJ4HNJ"
      #  是否匿名化用户 IP
      anonymizeIP = true
      #  是否遵循浏览器的 "Do Not Track" 设置
      respectDoNotTrack = false
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      # 自行托管追踪器时的主机路径
      server = ""
    # Plausible Analytics
    [params.analytics.plausible]
      dataDomain = ""
    # Yandex Metrica
    [params.analytics.yandexMetrica]
      id = ""

  #  Cookie 许可配置
  [params.cookieconsent]
    enable = true

  #  第三方库文件的 CDN 设置
  [params.cdn]
    # CDN 数据文件名称, 默认不启用
    # ["jsdelivr.yml"]
    # 可以在你的项目下相同路径存放你自己的数据文件:
    # "assets/data/cdn/"
    data = ""

  #  兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false

# Hugo 解析文档的配置
[markup]
  _merge = "shallow"
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置
[Permalinks]
  # posts = ":year/:month/:contentbasename"
  posts = ":contentbasename"

# 隐私信息配置
[privacy]
  #  Google Analytics 相关隐私设置 (也能在 params.analytics.google 配置)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    # ...
  [privacy.youtube]
    # ...

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  _merge = "shallow"

[taxonomies]
  _merge = "shallow"